# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

references:
  attach_workspace: &attach_workspace
    attach_workspace:
      at: .

jobs:
  build:
    docker:
        - image: circleci/node:10.16.0-stretch
    steps:
      - checkout      
      - *attach_workspace
      - run:
          name: Installing dependency
          working_directory: ~/project
          command: |
            npm i
            npm run build

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  build-and-deploy:
    # Run the welcome/run job in its own container
    jobs:
      - build